
FROM python:3.9


WORKDIR /app


COPY main.py EndpointHandling.py influxhandling.py mls.py /app/


RUN pip install --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org opcua influxdb-client elementpath cryptography


CMD ["python", "main.py"]
